### ISSUE TITLE
opcode errors not propogating properly

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi-script#11]
> Nerdy nit: the script OP_IF OP_PUSH PUBKEY(YOU) should result in an unbalanced conditional (if without else) error, but instead its "STACK_ERR: Stack should finish with only one item on the stack"

**Comment by benalleng** [comment]
closed by f5c47bbd743d88b3709bed0eb4e971007bdeac88 still have the question about error heirarchy

**Comment by pinheadmz** [comment]
Unbalanced conditional is checked at the end of `EvalScript()`:

https://github.com/bitcoin/bitcoin/blob/85bcfeea23568053ea09013fb8263fa1511d7123/src/script/interpreter.cpp#L1231

... and then clean stack and result are checked by the calling function `ExecuteWitnessScript()` after `EvalScript()` returns:

https://github.com/bitcoin/bitcoin/blob/85bcfeea23568053ea09013fb8263fa1511d7123/src/script/interpreter.cpp#L1819-L1824



But casually though I feel like unbalanced conditional is like forgetting the `}` at the end of a block of javascript for example, it's more like a syntax error than a invalid result
