### ISSUE TITLE
Chapter 10 - All links say "Challenge 1"

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi-script#15]
From [Christoph's chapter 10 feedback](https://www.figma.com/design/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=9670-3299). All the script editor screens in chapter 10 say "Challenge 1"
![image](https://github.com/user-attachments/assets/3d27443f-0747-4464-b029-22b3352f964f)

For example, https://script.savingsatoshi.com/?lesson=CH10OAC2 vs https://script.savingsatoshi.com/?lesson=CH10OAC4
![image](https://github.com/user-attachments/assets/a9bcc38c-c4f0-4902-943f-53c1378d3c73)

**Comment by benalleng** [comment]
Closed with 926f2f655d4805a1e68329440ee76acf2c944483
